//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_First_Approch_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee_Details
    {
        [Key]
        public int Emp_id { get; set; }
        public string Emp_name { get; set; }
        public string Emp_dept { get; set; }
        public string Emp_Address { get; set; }
        public int Emp_salary { get; set; }
    }
}
